title: "The Skelton Research Group"
description: "First-principles materials modelling and structural dynamics"
lang: "en-GB"

plugins:
  - jekyll-remote-theme

remote_theme: skelton-group/jekyll-theme-slate-mod

navbar:
  - link: index.html
    text: "Home"
  - link: research.html
    text: "Research"
  - link: people.html
    text: "People"
  - link: publications.html
    text: "Publications"
  - link: opportunities.html
    text: "Opportunities"
  - link: contact.html
    text: "Contact"
